# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccview < Formula
  desc "Compact console monitor for Claude usage limits"
  homepage "https://github.com/merlindeep/claude-cost-viewer"
  version "0.1.0"
  license "0BSD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.1.0/ccview_0.1.0_darwin_amd64.tar.gz"
      sha256 "eefcd2f8653a7c2aeef5ca7bfeb6b3784f164274668858d7644afdc793087bb5"

      define_method(:install) do
        bin.install "ccview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.1.0/ccview_0.1.0_darwin_arm64.tar.gz"
      sha256 "21d67bdcb3f1d4440ef331b8145c669fb2a2c2c5ca4ea9dbf7c1cf07f4131333"

      define_method(:install) do
        bin.install "ccview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.1.0/ccview_0.1.0_linux_amd64.tar.gz"
      sha256 "631e7f79832a439b8afb5822d6617ae14625827ac0954c6c8fa0abbc80d01ad4"
      define_method(:install) do
        bin.install "ccview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.1.0/ccview_0.1.0_linux_arm64.tar.gz"
      sha256 "83294a7be1ba8d02274c8cf1e18e48df539175221e472fe2fa2dc46fc17f73b2"
      define_method(:install) do
        bin.install "ccview"
      end
    end
  end

  test do
    system "#{bin}/ccview", "version"
  end
end
