# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccview < Formula
  desc "Compact console monitor for Claude usage limits"
  homepage "https://github.com/merlindeep/claude-cost-viewer"
  version "0.1.1"
  license "0BSD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.1.1/ccview_0.1.1_darwin_amd64.tar.gz"
      sha256 "024c1434a03ea0743f11d321cf965faff1f956a7c95ff4ecbbd90012422a998c"

      define_method(:install) do
        bin.install "ccview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.1.1/ccview_0.1.1_darwin_arm64.tar.gz"
      sha256 "4ba6e2cfcfc463a23168df409c6d8df7579d985191bbefe2d8454eaeef40e822"

      define_method(:install) do
        bin.install "ccview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.1.1/ccview_0.1.1_linux_amd64.tar.gz"
      sha256 "73c9cd3a30af72cbded5293a9854c842369a3f155be3c734f0b60e13f514dd4c"
      define_method(:install) do
        bin.install "ccview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.1.1/ccview_0.1.1_linux_arm64.tar.gz"
      sha256 "e821645956ae7fad290254e978f0c2d083f868a47b5bfc29432ed9d6a3a22f68"
      define_method(:install) do
        bin.install "ccview"
      end
    end
  end

  test do
    system "#{bin}/ccview", "version"
  end
end
