# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccview < Formula
  desc "Compact console monitor for Claude usage limits"
  homepage "https://github.com/merlindeep/claude-cost-viewer"
  version "0.3.0"
  license "0BSD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.3.0/ccview_0.3.0_darwin_amd64.tar.gz"
      sha256 "e32d3fae7e50b6313e0ab924cd9c6e181c8648cb495db59a9e6c0b129d34e83e"

      define_method(:install) do
        bin.install "ccview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.3.0/ccview_0.3.0_darwin_arm64.tar.gz"
      sha256 "ea3eaa666adcf263f2dc3d3a139645d097e3d905e1aff7eef23ff6bf247edc7a"

      define_method(:install) do
        bin.install "ccview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.3.0/ccview_0.3.0_linux_amd64.tar.gz"
      sha256 "ad867de23bcf60d6376a78c91299f09b41bcba68861523f1b0efd2d932e3288d"
      define_method(:install) do
        bin.install "ccview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/merlindeep/claude-cost-viewer/releases/download/v0.3.0/ccview_0.3.0_linux_arm64.tar.gz"
      sha256 "4381259a2c9c70b5857b5e7724307215e8980dbc707c112b4abf8c921b695dc1"
      define_method(:install) do
        bin.install "ccview"
      end
    end
  end

  test do
    system "#{bin}/ccview", "version"
  end
end
